### ISSUE TITLE
Error when I run using both 'deepRL-alloc' & 'deepRL-sel'

### ISSUE THREAD

**Issue by akarsh16reddy** [Cloudslab/DLSF#10]
````
Starting fastStorage\2013-8_deepRL-alloc_deepRL-sel_200`
Ran python code : ../Deep-Learning/DeepRL.py
Creating VMs...
99%
Training
DL Loss = Init Loss
0 hr 5 min - 17
Cannot invoke "String.split(String)" because "result" is null
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at org.cloudbus.cloudsim.power.DRLVmAllocationPolicy.getNewVmPlacement(DRLVmAllocationPolicy.java:116)
	at org.cloudbus.cloudsim.power.DRLVmAllocationPolicy.optimizeAllocation(DRLVmAllocationPolicy.java:75)
	at org.cloudbus.cloudsim.power.DRLDatacenter.updateCloudletProcessing(DRLDatacenter.java:244)
	at org.cloudbus.cloudsim.Datacenter.processEvent(Datacenter.java:252)
	at org.cloudbus.cloudsim.core.SimEntity.run(SimEntity.java:426)
	at org.cloudbus.cloudsim.core.CloudSim.runClockTick(CloudSim.java:523)
	at org.cloudbus.cloudsim.core.CloudSim.run(CloudSim.java:887)
	at org.cloudbus.cloudsim.core.CloudSim.startSimulation(CloudSim.java:188)
	at org.cloudbus.cloudsim.examples.power.DeepRL.DeepRLRunner.startDynamic(DeepRLRunner.java:198)
	at org.cloudbus.cloudsim.examples.power.DeepRL.DeepRLRunner.start(DeepRLRunner.java:96)
	at org.cloudbus.cloudsim.examples.power.RunnerAbstract.<init>(RunnerAbstract.java:96)
	at org.cloudbus.cloudsim.examples.power.DeepRL.DeepRLRunner.<init>(DeepRLRunner.java:55)
	at org.cloudbus.cloudsim.examples.power.DeepRL.DeepRLRunner.main(DeepRLRunner.java:367)

Process finished with exit code 0
```

**Comment by shreshthtuli** [comment]
Hi. This repository has been depracated. For Deep Reinforcement Learning based scheduling in simulated fog environments, please go through the new codebase here: https://github.com/imperial-qore/COSCO.
